

SELECT *
FROM PER_ALL_PEOPLE_F
--WHERE FULL_NAME LIKE '%CHICA, Ms. ANGIE MAE ARENAS%'


SELECT LOCAL_NAME
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'

SELECT* 
FROM PER_ALL_FND_USERS

CREATE OR REPLACE VIEW PER_ALL_FND_USERS AS
SELECT  P.PERSON_ID,
        P.EFFECTIVE_START_DATE,
        P.EFFECTIVE_END_DATE,
        P.DATE_OF_BIRTH,
        P.EMPLOYEE_NUMBER,
        P.FULL_NAME,
        P.SEX,
        P.ATTRIBUTE28,
        P.ATTRIBUTE29,
        P.LAST_UPDATE_DATE,
        P.LAST_UPDATE_LOGIN,
        P.CREATED_BY,
        P.CREATION_DATE,
        P.ORIGINAL_DATE_OF_HIRE,
        F.USER_ID,
        F.USER_NAME,
        F.DESCRIPTION,
        F.EMPLOYEE_ID
FROM PER_ALL_PEOPLE_F P JOIN  FND_USER F 
ON  P.PERSON_ID= F.EMPLOYEE_ID 

SELECT *
FROM PER_ALL_PEOPLE_F
WHERE ATTRIBUTE28 = 'REGULAR'
AND CREATED_BY = 5023
AND ATTRIBUTE29= 'BDO'

SELECT *  FROM PER_ALL_FND_USERS


SELECT LOCATION_ID, DEPARTMENT_NAME
FROM DEPARTMENTS 
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME ='Executive')



SELECT USER_NAME, DESCRIPTION
FROM FND_USER 
WHERE EMPLOYEE_ID in (SELECT PERSON_ID FROM PER_ALL_PEOPLE_F WHERE FULL_NAME LIKE '%MARK%' )
 
SELECT * 
FROM PER_ALL_PEOPLE_F 
WHERE FULL_NAME LIKE '%NILLO%MARK%'


SELECT JOB_TITLE FROM JOBS WHERE JOB_ID IN  
(SELECT  JOB_ID FROM EMPLOYEES WHERE
FIRST_NAME LIKE 'St%')


SELECT* 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE D.DEPARTMENT_ID= E.DEPARTMENT_ID

SELECT *
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'

SELECT *
FROM FND_USER
WHERE DESCRIPTION LIKE '%XXTIP JOB User%'

SELECT * FROM PER_ALL_PEOPLE_F
WHERE PERSON_ID LIKE '%12287%'

SELECT *
FROM FND_USER FND 
 RIGHT JOIN PER_ALL_PEOPLE_F PER
ON PER.PERSON_ID = FND.EMPLOYEE_ID 
--WHERE 1=1
WHERE PER.ATTRIBUTE29 ='BPI'
AND  PER.ATTRIBUTE28 ='SEPARATED'
AND PER.DATE_OF_BIRTH= TO_DATE('1999','RR')


SELECT *
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'



SELECT CREATED_BY , COUNT(CREATED_BY) CREATED  FROM PER_ALL_PEOPLE_F
WHERE EFFECTIVE_START_DATE BETWEEN DATE '2000-12-01' AND DATE '2022-12-01'
GROUP BY CREATED_BY 


SELECT *  FROM PER_ALL_PEOPLE_F
WHERE ORIGINAL_DATE_OF_HIRE BETWEEN DATE '2021-11-01' AND DATE '2021-11-30'
ORDER BY ORIGINAL_DATE_OF_HIRE DESC
 



SELECT *
FROM PER_ALL_PEOPLE_F
--WHERE FULL_NAME LIKE '%CHICA, Ms. ANGIE MAE ARENAS%'


SELECT LOCAL_NAME
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'

SELECT* 
FROM PER_ALL_FND_USERS

CREATE OR REPLACE VIEW PER_ALL_FND_USERS AS
SELECT  P.PERSON_ID,
        P.EFFECTIVE_START_DATE,
        P.EFFECTIVE_END_DATE,
        P.DATE_OF_BIRTH,
        P.EMPLOYEE_NUMBER,
        P.FULL_NAME,
        P.SEX,
        P.ATTRIBUTE28,
        P.ATTRIBUTE29,
        P.LAST_UPDATE_DATE,
        P.LAST_UPDATE_LOGIN,
        P.CREATED_BY,
        P.CREATION_DATE,
        P.ORIGINAL_DATE_OF_HIRE,
        F.USER_ID,
        F.USER_NAME,
        F.DESCRIPTION,
        F.EMPLOYEE_ID
FROM PER_ALL_PEOPLE_F P JOIN  FND_USER F 
ON  P.PERSON_ID= F.EMPLOYEE_ID 

SELECT *
FROM PER_ALL_PEOPLE_F
WHERE ATTRIBUTE28 = 'REGULAR'
AND CREATED_BY = 5023


SELECT *
FROM FND_USER
 
SELECT * 
FROM PER_ALL_PEOPLE_F P JOIN  FND_USER F 
ON  P.PERSON_ID= F.EMPLOYEE_ID 

SELECT* 
FROM EMPLOYEES E, DEPARTMENTS D
WHERE D.DEPARTMENT_ID= E.DEPARTMENT_ID

SELECT *
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'

SELECT * 
FROM FND_USER
WHERE DESCRIPTION LIKE '%0001%'

SELECT *
FROM FND_USER FND 
JOIN PER_ALL_PEOPLE_F PER
ON PER.PERSON_ID = FND.EMPLOYEE_ID 
--WHERE 1=1
WHERE PER.ATTRIBUTE29 ='BPI'
AND  PER.ATTRIBUTE28 ='SEPARATED'
--AND PER.DATE_OF_BIRTH= TO_DATE('1999','RR')


SELECT FULL_NAME, TO_CHAR (DATE_OF_BIRTH,'YYYY') YEAR_OF_BIRTH
FROM PER_ALL_PEOPLE_F
WHERE FULL_NAME LIKE '%CHICA%SAMIRA%'

SELECT *  FROM JOB_HISTORY
WHERE START_DATE BETWEEN TO_DATE('1997','YYYY') AND TO_DATE('1999','YYYY')

SELECT JOB_TITLE, FIRST_NAME||' '||LAST_NAME LOCAL_NAME
FROM EMPLOYEES EMP, JOBS JOB 
WHERE JOB.JOB_ID= EMP.JOB_ID
AND EMP.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID  FROM JOB_HISTORY
WHERE START_DATE BETWEEN TO_DATE('1997','YYYY') AND TO_DATE('1999','YYYY'))


SELECT *  FROM EMPLOYEES

SELECT *  FROM DEPARTMENTS

SELECT *  FROM COUNTRIES

SELECT *  FROM LOCATIONS

SELECT *  FROM REGIONS

SELECT  COU.COUNTRY_ID, REG.REGION_NAME, EMP.FIRST_NAME, COU.COUNTRY_NAME, REG.CLIMATE_TYPE
FROM    EMPLOYEES EMP,
        DEPARTMENTS DEPT,
        COUNTRIES COU,
        REGIONS REG,
        LOCATIONS LOC
WHERE 1=1
AND EMP.DEPARTMENT_ID= DEPT.DEPARTMENT_ID
AND DEPT.LOCATION_ID= LOC.LOCATION_ID
AND LOC.COUNTRY_ID= COU.COUNTRY_ID
AND  COU.REGION_ID= REG.REGION_ID
ORDER BY FIRST_NAME 

