CREATE OR REPLACE VIEW PER_ALL_PEOPE_FND_USER
AS
     SELECT PER.FULL_NAME, FND.USER_NAME, PER.DATE_OF_BIRTH
       FROM PER_ALL_PEOPLE_F PER
            LEFT JOIN FND_USER FND ON PER.PERSON_ID = FND.EMPLOYEE_ID
   ORDER BY PER.START_DATE DESC;

----------------------------------------------------------------------------

CREATE OR REPLACE VIEW PER_ALL_FND_USERS
AS
   SELECT P.PERSON_ID,
          P.EFFECTIVE_START_DATE,
          P.EFFECTIVE_END_DATE,
          P.DATE_OF_BIRTH,
          P.EMPLOYEE_NUMBER,
          P.FULL_NAME,
          P.SEX,
          P.ATTRIBUTE28,
          P.ATTRIBUTE29,
          P.LAST_UPDATE_DATE,
          P.LAST_UPDATE_LOGIN,
          P.CREATED_BY,
          P.CREATION_DATE,
          P.ORIGINAL_DATE_OF_HIRE,
          F.USER_ID,
          F.USER_NAME,
          F.DESCRIPTION,
          F.EMPLOYEE_ID
     FROM PER_ALL_PEOPLE_F P JOIN FND_USER F ON P.PERSON_ID = F.EMPLOYEE_ID