CREATE OR REPLACE PROCEDURE DEPT_PROC (DP NUMBER)

AS

   CURSOR SAMPLE_CUR
   IS
      SELECT FIRST_NAME, LAST_NAME
        FROM EMPLOYEES
       WHERE DEPARTMENT_ID= DP;
       
       SAMPLE_REC   SAMPLE_CUR%ROWTYPE;

BEGIN
   OPEN SAMPLE_CUR;

   LOOP
      FETCH SAMPLE_CUR INTO SAMPLE_REC;

      EXIT WHEN SAMPLE_CUR%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(SAMPLE_REC.LAST_NAME || ', ' || SAMPLE_REC.FIRST_NAME);
   END LOOP;
END;


CREATE OR REPLACE FUNCTION DEPT_FUNC (DF NUMBER)
RETURN VARCHAR2
AS

   CURSOR SAMPLE_CUR
   IS
      SELECT FIRST_NAME, LAST_NAME
        FROM EMPLOYEES
       WHERE DEPARTMENT_ID= DF;
       
       SAMPLE_REC   SAMPLE_CUR%ROWTYPE;

BEGIN
   OPEN SAMPLE_CUR;

   LOOP
      FETCH SAMPLE_CUR INTO SAMPLE_REC;

      EXIT WHEN SAMPLE_CUR%NOTFOUND;
      RETURN(SAMPLE_REC.LAST_NAME || ', ' || SAMPLE_REC.FIRST_NAME);
   END LOOP;
END;