CREATE OR REPLACE PROCEDURE PROC_UPDATE(PROC_ID NUMBER, 
                                         PROC_NAME VARCHAR,
                                         PROC_VALUE VARCHAR)
IS 


BEGIN
    IF PROC_NAME= 'NAME' THEN
        UPDATE CUSTOMERS
        SET NAME= PROC_VALUE, LAST_UPDATE_DATE= SYSDATE 
        WHERE ID= PROC_ID;
       COMMIT;
       
    ELSIF PROC_NAME= 'AGE' THEN
        UPDATE CUSTOMERS
        SET AGE= PROC_VALUE, LAST_UPDATE_DATE= SYSDATE 
        WHERE ID= PROC_ID;
       COMMIT;
    ELSIF PROC_NAME= 'ADDRESS' THEN
        UPDATE CUSTOMERS
        SET ADDRESS= PROC_VALUE, LAST_UPDATE_DATE= SYSDATE
        WHERE ID= PROC_ID;
       COMMIT;
       
    ELSIF PROC_NAME= 'SALARY' THEN
        UPDATE CUSTOMERS
        SET SALARY= PROC_VALUE, LAST_UPDATE_DATE= SYSDATE 
        WHERE ID= PROC_ID;
       COMMIT;
   
END IF;
END;
