CREATE OR REPLACE PROCEDURE WELCOME_MSG1 (V_NAME VARCHAR2)
IS 
BEGIN
DBMS_OUTPUT.PUT_LINE('WELCOME '||V_NAME);
END;


CREATE OR REPLACE FUNCTION WELCOME_MSG2 (V_NAME VARCHAR2) 
RETURN VARCHAR2
IS 
BEGIN
RETURN ('WELCOME '||V_NAME);
END;
