--1

DECLARE
   V_LNAME    VARCHAR2 (20);
   V_SALARY   VARCHAR2 (20);
BEGIN
   SELECT LAST_NAME, SALARY
     INTO V_LNAME, V_SALARY
     FROM EMPLOYEES
    WHERE JOB_ID = 'AD_PRES';

   DBMS_OUTPUT.PUT_LINE (
      'LAST NAME: ' || V_LNAME || ' ' || 'SALARY: ' || V_SALARY);
END;


--2

DECLARE
   COUNTED_EMP   VARCHAR2 (10);
BEGIN
   SELECT COUNT (EMPLOYEE_ID)
     INTO COUNTED_EMP
     FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 50;

   DBMS_OUTPUT.PUT_LINE ('COUNTED EMPLOYEES IN DEPT.50: ' || COUNTED_EMP);
END;


--3

DECLARE
   A   NUMBER;
   B   NUMBER;
   C   NUMBER;
BEGIN
   FOR A IN 1 .. 5
   LOOP
      FOR B IN 1 .. 5
      LOOP
         C := A * B;
         DBMS_OUTPUT.PUT_LINE (A || 'x' || B || ' :' || C);
      END LOOP;
   END LOOP;
END;

--4

DECLARE
   B   NUMBER:= 1;
BEGIN

   WHILE B <= 25
   LOOP
      DBMS_OUTPUT.PUT_LINE (B);
      B := B + 2;
   END LOOP;
END;



DECLARE
   A   NUMBER;
BEGIN
   FOR A IN 1 .. 25
   LOOP
      IF MOD (A, 2) != 0
      THEN
         DBMS_OUTPUT.PUT_LINE (A);
      END IF;
   END LOOP;
END;

--5

DECLARE
   V_FNAME         VARCHAR2 (20);
   V_LNAME         VARCHAR2 (20);
   V_EMPLOYEE_ID   NUMBER;
BEGIN
   SELECT FIRST_NAME, LAST_NAME
     INTO V_FNAME, V_LNAME
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = '&V_EMPLOYEE_ID';

   DBMS_OUTPUT.PUT_LINE (
      'FIRST NAME: ' || V_FNAME || ' LAST NAME: ' || V_LNAME);
END;


--6

DECLARE
   UPDATED_SAL   NUMBER;
BEGIN
   UPDATE EMPLOYEES
      SET SALARY = SALARY + 500
    WHERE DEPARTMENT_ID = 120;

   IF SQL%NOTFOUND
   THEN
      DBMS_OUTPUT.PUT_LINE ('NO UPDATE');
   ELSIF SQL%FOUND
   THEN
      UPDATED_SAL := SQL%ROWCOUNT;
      DBMS_OUTPUT.PUT_LINE ('UPDATED: ' || UPDATED_SAL || ' RECORD.');
   END IF;
END;

--7

BEGIN
   FOR A IN REVERSE 1 .. 10
   LOOP
      DBMS_OUTPUT.PUT_LINE (A);
   END LOOP;
END;


--8
DECLARE
   MAX_EMP   NUMBER;
BEGIN
   SELECT MAX (EMPLOYEE_ID) MAXEMPID INTO MAX_EMP FROM EMPLOYEES;

   DBMS_OUTPUT.PUT_LINE ('MAXIMUM EMPLOYEE ID: ' || MAX_EMP);
END;


--9

DECLARE
   V_SALARY   VARCHAR2 (20);
   V_EMP_ID   NUMBER;
BEGIN
   SELECT SALARY
     INTO V_SALARY
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = '&V_EMP_ID';

   DBMS_OUTPUT.PUT_LINE ('SALARY: ' || V_SALARY);

   CASE
      WHEN V_SALARY < 50000
      THEN
         DBMS_OUTPUT.PUT_LINE ('SALARY LESS THAN 50,000');
      ELSE
         DBMS_OUTPUT.PUT_LINE ('SALARY MORE THAN 50,000');
   END CASE;
END;


--10

SET SERVEROUTPUT ON;

DECLARE
   V_FIRST_NAME   EMPLOYEES.FIRST_NAME%TYPE;
   V_LAST_NAME    EMPLOYEES.LAST_NAME%TYPE;
   V_JOB_ID       EMPLOYEES.JOB_ID%TYPE;
BEGIN
   SELECT FIRST_NAME, LAST_NAME, JOB_ID
     INTO V_FIRST_NAME, V_LAST_NAME, V_JOB_ID
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 200;

   DBMS_OUTPUT.PUT_LINE (
      V_FIRST_NAME || ' ' || V_LAST_NAME || ' ' || V_JOB_ID);
END;