DECLARE
   INPUT   VARCHAR2 (20) := '&NAME';
   REV     VARCHAR2 (50) := '';
BEGIN
   FOR I IN REVERSE 1 .. LENGTH (INPUT)
   LOOP
      REV := REV || SUBSTR (INPUT, I, 1);
   END LOOP;

   DBMS_OUTPUT.PUT_LINE (REV);
END;