--1

DECLARE
   CURSOR C_EMP
   IS
      SELECT EMPLOYEE_ID, LAST_NAME
        FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 30;

BEGIN
   FOR EMP IN C_EMP
   LOOP
      DBMS_OUTPUT.PUT_LINE (EMP.EMPLOYEE_ID || ' ' || EMP.LAST_NAME);
   END LOOP;
END;

--2

DECLARE
   V_EMPID   EMPLOYEES.EMPLOYEE_ID%TYPE;
   V_LNAME   EMPLOYEES.LAST_NAME%TYPE;

   CURSOR C_EMP
   IS
      SELECT EMPLOYEE_ID, LAST_NAME
        FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 30;

BEGIN
   OPEN C_EMP;

   LOOP
      FETCH C_EMP
         INTO V_EMPID, V_LNAME;

      EXIT WHEN C_EMP%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE (V_EMPID || ' ' || V_LNAME);
   END LOOP;

   CLOSE C_EMP;
END;


--3

DECLARE
   V_EMPID   EMPLOYEES.EMPLOYEE_ID%TYPE;
   V_FNAME   EMPLOYEES.FIRST_NAME%TYPE;
   V_LNAME   EMPLOYEES.LAST_NAME%TYPE;

   CURSOR C_EMP
   IS
      SELECT FIRST_NAME, LAST_NAME
        FROM EMPLOYEES
       WHERE EMPLOYEE_ID = '&V_EMPID';

BEGIN
   OPEN C_EMP;

   LOOP
      FETCH C_EMP
         INTO V_FNAME, V_LNAME;

      DBMS_OUTPUT.PUT_LINE ('FIRST NAME: ' || V_FNAME);
      DBMS_OUTPUT.PUT_LINE ('LAST NAME: ' || V_LNAME);
      EXIT WHEN C_EMP%NOTFOUND;
   END LOOP;

   CLOSE C_EMP;
END;


--4

DECLARE
   V_LNAME    EMPLOYEES.LAST_NAME%TYPE;
   V_JOBID    EMPLOYEES.JOB_ID%TYPE;
   V_SALARY   EMPLOYEES.SALARY%TYPE;
   V_EMPID    NUMBER;
BEGIN
   SELECT LAST_NAME, JOB_ID, SALARY
     INTO V_LNAME, V_JOBID, V_SALARY
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = '&V_EMPID';

   DBMS_OUTPUT.PUT_LINE (V_LNAME || V_JOBID || V_SALARY);
EXCEPTION
   WHEN TOO_MANY_ROWS
   THEN
      DBMS_OUTPUT.PUT_LINE ('TOO MANY ROWS');
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.PUT_LINE ('NO DATA FOUND');
END;

--5

DECLARE
   CURSOR C_EMP
   IS
      SELECT EMPLOYEE_ID, LAST_NAME
        FROM EMPLOYEES
       WHERE DEPARTMENT_ID = 30;

   EMP_REC   C_EMP%ROWTYPE;
BEGIN
   OPEN C_EMP;

   LOOP
      FETCH C_EMP INTO EMP_REC;

      EXIT WHEN C_EMP%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE (EMP_REC.EMPLOYEE_ID || ' ' || EMP_REC.LAST_NAME);
   END LOOP;

   CLOSE C_EMP;
END;

--6

CREATE OR REPLACE PROCEDURE MY_PROCEDURE1
AS
BEGIN
   DBMS_OUTPUT.PUT_LINE ('TODAY IS: ' || SYSDATE);
END;

--7

CREATE OR REPLACE PROCEDURE MY_PROCEDURE2 (EMP_ID NUMBER)
AS
   V_FNAME   VARCHAR2 (20);
   V_LNAME   VARCHAR2 (20);
BEGIN
   SELECT FIRST_NAME, LAST_NAME
     INTO V_FNAME, V_LNAME
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMP_ID;

   DBMS_OUTPUT.PUT_LINE (
      'GOOD D A Y!!!  ' || V_FNAME || ' ' || V_LNAME || ' :) ');
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      DBMS_OUTPUT.PUT_LINE ('NO RECORD FOUND!');
END;

--8

CREATE OR REPLACE FUNCTION ISEVEN1 (P_INPUT IN NUMBER)
   RETURN VARCHAR2
AS
   V_RESULT   VARCHAR2 (10);
BEGIN
   IF (P_INPUT MOD 2) = 0
   THEN
      V_RESULT := 'TRUE';
   ELSE
      V_RESULT := 'FALSE';
   END IF;

   RETURN V_RESULT;
END;