CREATE OR REPLACE PROCEDURE TIPKT.HIKE_RESERVE_LIST_UPDATE3 (
   UPDATE_NAME       VARCHAR,
   UPDATE_COL        VARCHAR,
   UPDATE_COL_VAL    VARCHAR)
IS
   V_NUM_OF_JOINERS   NUMBER;
   V_MOUNTAIN_PICK    VARCHAR (30);
BEGIN
   IF UPDATE_COL = 'MOUNTAIN_PICK'
   THEN
      UPDATE HIKE_RESERVATION
         SET MOUNTAIN_PICK = UPDATE_COL_VAL
       WHERE NAME = UPDATE_NAME;
       
   ELSIF UPDATE_COL = 'DATE_OF_HIKE'
   THEN
      UPDATE HIKE_RESERVATION
         SET DATE_OF_HIKE = UPDATE_COL_VAL
       WHERE NAME = UPDATE_NAME;
       
   ELSIF UPDATE_COL = 'NUM_OF_JOINERS'
   THEN
      UPDATE HIKE_RESERVATION
         SET NUM_OF_JOINERS = UPDATE_COL_VAL
       WHERE NAME = UPDATE_NAME;
 END IF;
END;