CREATE OR REPLACE PROCEDURE HIKE_RESERVE_LIST_CONFIRM (T_NUM NUMBER)
IS
   V_NUM_OF_JOINERS   VARCHAR2 (30);
   V_MOUNTAIN_PICK    VARCHAR2 (30);
   V_DOWNPAYMENT      VARCHAR2 (30);
   V_STATUS           VARCHAR2 (30);
BEGIN
   SELECT NUM_OF_JOINERS,
          MOUNTAIN_PICK,
          DOWNPAYMENT,
          STATUS
     INTO V_NUM_OF_JOINERS,
          V_MOUNTAIN_PICK,
          V_DOWNPAYMENT,
          V_STATUS
     FROM HIKE_RESERVATION
    WHERE TRANSACTION_NUM = T_NUM;

   IF V_STATUS = 'JOINED'
      THEN
         UPDATE HIKE_RESERVATION
            SET STATUS = 'CONFIRMED',
                DOWNPAYMENT = 'Y',
                LAST_UPDATE_DATE = SYSDATE
          WHERE TRANSACTION_NUM = T_NUM AND STATUS = 'JOINED';

         SELECT NUM_OF_JOINERS, MOUNTAIN_PICK
           INTO V_NUM_OF_JOINERS, V_MOUNTAIN_PICK
           FROM HIKE_RESERVATION
          WHERE TRANSACTION_NUM = T_NUM;

         UPDATE HIKE_RESERVATION_LIST
            SET SLOTS = SLOTS - V_NUM_OF_JOINERS
          WHERE MT_ID = V_MOUNTAIN_PICK;

         COMMIT;
         DBMS_OUTPUT.PUT_LINE ('RESERVATION CONFIRMED!');
      ELSE
         DBMS_OUTPUT.PUT_LINE ('ALREADY CONFIRMED!');
      END IF;
END;