CREATE OR REPLACE TRIGGER TIPKT.RESTRICT_SLOTS
   BEFORE INSERT OR UPDATE OF SLOTS
   ON TIPKT.HIKE_RESERVATION_LIST
   FOR EACH ROW
BEGIN
   IF   :NEW.SLOTS <0   
  
   THEN
      RAISE_APPLICATION_ERROR(-20222, 'There are currently no available slots.');
   
   END IF;
   END;